import * as crypto from "crypto";

// Adjectives (you can expand this list)
const adjectives: string[] = [
  "admiring",
  "adoring",
  "agitated",
  "amazing",
  "amused",
  "angry",
  "astonishing",
  "attentive",
  "aweful",
  "awkward",
  "blissful",
  "bold",
  "boring",
  "brave",
  "breezy",
  "bright",
  "calm",
  "caring",
  "charming",
  "cheerful",
  "clever",
  "cocky",
  "confident",
  "cool",
  "cranky",
  "crazy",
  "creative",
  "cynical",
  "dazzling",
  "delightful",
  "depressed",
  "determined",
  "diligent",
  "disgusted",
  "distracted",
  "dreamy",
  "eager",
  "ecstatic",
  "elated",
  "elegant",
  "energetic",
  "envious",
  "excited",
  "exuberant",
  "fabulous",
  "fair",
  "faithful",
  "fearful",
  "fierce",
  "flustered",
  "focused",
  "foolish",
  "frantic",
  "friendly",
  "frightened",
  "gleeful",
  "glorious",
  "gloomy",
  "good",
  "grateful",
  "grief",
  "grumpy",
  "happy",
  "harmonious",
  "hateful",
  "healthy",
  "helpful",
  "helpless",
  "hesitant",
  "horrible",
  "hungry",
  "hurt",
  "hysterical",
  "idiotic",
  "ignorant",
  "ill",
  "impressed",
  "insecure",
  "inspired",
  "intense",
  "interested",
  "intrigued",
  "irate",
  "irritable",
  "isolated",
  "joyful",
  "jolly",
  "jovial",
  "judgmental",
  "keen",
  "kind",
  "lazy",
  "lethargic",
  "lively",
  "lonely",
  "loving",
  "lucky",
  "mad",
  "magnificent",
  "manic",
  "mean",
  "melancholy",
  "mischievous",
  "moody",
  "morbid",
  "motivated",
  "mystified",
  "nasty",
  "nervous",
  "nice",
  "nosy",
  "numb",
  "obedient",
  "obnoxious",
  "optimistic",
  "outraged",
  "panicked",
  "peaceful",
  "pensive",
  "pessimistic",
  "petrified",
  "playful",
  "pleasant",
  "proud",
  "puzzled",
  "quiet",
  "rageful",
  "relieved",
  "remorseful",
  "restless",
  "rude",
  "sad",
  "sarcastic",
  "satisfied",
  "scared",
  "selfish",
  "serene",
  "serious",
  "shocked",
  "shy",
  "silly",
  "sleepy",
  "smug",
  "solemn",
  "sorrowful",
  "spirited",
  "spiteful",
  "stable",
  "stern",
  "strange",
  "stressed",
  "stubborn",
  "stupid",
  "submissive",
  "sulky",
  "sullen",
  "surprised",
  "suspicious",
  "sympathetic",
  "tense",
  "terrible",
  "terrified",
  "thankful",
  "thoughtful",
  "tired",
  "tolerant",
  "tranquil",
  "troubled",
  "trusting",
  "truthful",
  "uncomfortable",
  "uneasy",
  "upset",
  "valued",
  "vengeful",
  "vibrant",
  "vicious",
  "victorious",
  "vigilant",
  "vulnerable",
  "warm",
  "weary",
  "weepy",
  "wicked",
  "wild",
  "willing",
  "wise",
  "witty",
  "wonderful",
  "worried",
  "wrathful",
  "zealous",
];

// Famous Scientists and Characters (you can expand this list)
const names: string[] = [
  "albert-einstein",
  "marie-curie",
  "isaac-newton",
  "galileo-galilei",
  "charles-darwin",
  "ada-lovelace",
  "alan-turing",
  "stephen-hawking",
  "nikola-tesla",
  "jane-goodall",
  "rosa-parks",
  "martin-luther-king-jr",
  "nelson-mandela",
  "malala-yousafzai",
  "leonardo-da-vinci",
  "william-shakespeare",
  "cleopatra",
  "genghis-khan",
  "napoleon",
  "queen-victoria",
  "abraham-lincoln",
  "george-washington",
  "socrates",
  "plato",
  "aristotle",
  "confucius",
  "buddha",
  "jesus",
  "mohammed",
  "odin",
  "thor",
  "zeus",
  "athena",
  "hades",
  "harry-potter",
  "hermione-granger",
  "ron-weasley",
  "frodo-baggins",
  "bilbo-baggins",
  "gandalf",
  "aragorn",
  "luke-skywalker",
  "darth-vader",
  "princess-leia",
  "sherlock-holmes",
  "dr-watson",
  "elizabeth-bennet",
  "mr-darcy",
  "romeo",
  "juliet",
  "hamlet",
  "macbeth",
  "ophelia",
];

function generateDockerName(): string {
  const adjective = adjectives[Math.floor(Math.random() * adjectives.length)];
  const name = names[Math.floor(Math.random() * names.length)];
  return `${adjective}-${name}`;
}

// Example usage:
// for (let i = 0; i < 10; i++) {
//   console.log(generateDockerName());
// }

// --- Optional: Using crypto for more "random" selection ---
function generateDockerNameCrypto(): string {
  const adjectiveIndex = crypto.randomInt(0, adjectives.length);
  const nameIndex = crypto.randomInt(0, names.length);
  return `${adjectives[adjectiveIndex]}-${names[nameIndex]}`;
}

console.log("\nUsing crypto for randomness:");
// for (let i = 0; i < 10; i++) {
//   console.log(generateDockerNameCrypto());
// }

export { generateDockerName, generateDockerNameCrypto };
